name: Deploy Prod to ECS

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/custom-gh-cicd-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Use staged-tag image
        run: |
          REGISTRY='${{ steps.login-ecr.outputs.registry }}'
          REPOSITORY='${{ vars.ECR_REPOSITORY }}'
          STAGED_TAG='staged-tag'

          DIGEST="$(aws ecr describe-images \
            --repository-name "$REPOSITORY" \
            --image-ids imageTag="$STAGED_TAG" \
            --query 'imageDetails[0].imageDigest' \
            --output text)"
          echo "IMAGE_URI=$REGISTRY/$REPOSITORY@$DIGEST" >> "$GITHUB_ENV"

      - name: Render ECS task definition (image)
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/ecs-task-def.json
          container-name: alpha-vitrina-mp
          image: ${{ env.IMAGE_URI }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          cluster: ${{ vars.ECS_CLUSTER }}
          service: ${{ vars.ECS_SERVICE_VITRINA_MP }}
          wait-for-service-stability: true
